#!/bin/bash
input=$1
convert ./scans/$input -fuzz 28% -trim +repage ./scans/prepared_$input &&
# /bin/sh deskewstep.sh $input &> /dev/null &&
./deskew -o ./scans/deskewed_$input ./scans/prepared_$input &> /dev/null &&
convert  ./scans/deskewed_$input  -level 15%,80%  ./scans/leveled_$input &&
convert ./scans/leveled_$input -crop `convert ./scans/leveled_$input -virtual-pixel edge -fuzz 90% -trim -format '%[fx:w+240]x%[fx:h+240)]+%[fx:page.x-120]+%[fx:page.y-120]' info:` +repage ./output/out_$input &&
rm ./scans/deskewed_$input ./scans/prepared_$input ./scans/leveled_$input &&
echo out_$input
