#!/bin/bash
input=$1
scanimage -d "brother3:bus2;dev1" -l 10 -t 10 -y 280 -x 190 --resolution=200 --format=jpeg > ./scans/$input &&

convert ./scans/$input -crop `convert ./scans/$input -virtual-pixel edge -fuzz 50% -trim -format '%[fx:w+400]x%[fx:h+400)]+%[fx:page.x-200]+%[fx:page.y-200]' info:` +repage ./scans/prepared_$input  &&

./deskew -o ./scans/deskewed_$input ./scans/prepared_$input &> /dev/null &&
convert  ./scans/deskewed_$input  -level 15%,80%  ./scans/leveled_$input &&
cp ./scans/leveled_$input ./output/out_$input &&
##first crop
#convert ./scans/leveled_$input -crop `convert ./scans/leveled_$input -virtual-pixel edge -fuzz 99% -trim -format '%[fx:w+400]x%[fx:h+400)]+%[fx:page.x-200]+%[fx:page.y-200]' info:` +repage ./scans/firstcrop_$input  &&
#cp ./scans/firstcrop_$input ./output/out_$input &&
#second crop
#convert ./scans/firstcrop_$input -crop `convert ./scans/firstcrop_$input -virtual-pixel edge -fuzz 99% -trim -format '%[fx:w+400]x% [fx:h+400)]+%[fx:page.x-200]+%[fx:page.y-200]' info:`+repage ./scans/secondcrop_$input &&
#cp ./scans/secondcrop_$input ./output/out_$input &&

#rm ./scans/deskewed_$input ./scans/prepared_$input ./scans/leveled_$input ./scans/firstcrop_$input &&
echo out_$input
